# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
# NextGen Smart Variants - Advanced Product Variant Visualization System

client_id = "7d73faef9f5579199909a48cf7ce9def"
name = "NextGen Smart Variants"
application_url = "https://productimagevariant-oiqs059h6-ustrendyim-apps-projects.vercel.app"
embedded = true

[app_info]
app_icon = "https://cdn.shopify.com/s/files/1/0234/5678/files/nextgen-variants-icon.png"
contact_email = "info@webtorn.com"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

# Product and variant related webhooks
[[webhooks.subscriptions]]
topics = ["products/create", "products/update", "products/delete"]
uri = "/webhooks/products"

# GDPR Mandatory Compliance Webhooks
[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks/compliance"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_themes,write_themes,read_inventory,write_inventory"

[auth]
redirect_urls = [ "https://productimagevariant-oiqs059h6-ustrendyim-apps-projects.vercel.app/auth" ]
